class CFG:

  SEED = 42

  cat_params_1 = {
                'n_estimators':5000,
                'learning_rate': 0.07,
                "eval_metric" : 'F1',
                'loss_function':'Logloss',
                'random_seed':SEED,
                "scale_pos_weight":3.8,
                'metric_period':500,
                'od_wait':500,
                'task_type':'GPU',
                'depth': 8}

  cat_params_2 = {
                'n_estimators':5000,
                'learning_rate': 0.07,
                "eval_metric" : 'F1',
                'loss_function':'Logloss',
                'random_seed':SEED,
                "scale_pos_weight":3.8,
                'metric_period':500,
                'od_wait':500,
                'task_type':'GPU',
                'depth': 8}

  lgb_params_1 = {
                    'objective':'binary',
                    'boosting_type':'gbdt',
                    'n_jobs':-1,
                    'learning_rate':0.01,
                    'num_leaves': 2**6,
                    'max_depth':-1,
                    "scale_pos_weight":3.9,
                    'tree_learner':'serial',
                    'colsample_bytree': 0.7,
                    'subsample_freq':1,
                    'subsample':1,
                    'n_estimators':800,
                    'max_bin':255,
                    'verbose':-1,
                    'seed': SEED}

  lgb_params_2 = {
                    'objective':'binary',
                    'boosting_type':'gbdt',
                    'n_jobs':-1,
                    'learning_rate':0.01,
                    'num_leaves': 2**6,
                    'max_depth':-1,
                    "scale_pos_weight":4,
                    'tree_learner':'serial',
                    'colsample_bytree': 0.7,
                    'subsample_freq':1,
                    'subsample':1,
                    'n_estimators':800,
                    'max_bin':255,
                    'verbose':-1,
                    'seed': SEED} 
      
  xgb_params_1 ={
        "n_estimators":2000,
        "max_depth":12, 
        "learning_rate":0.02, 
        "subsample":0.8,
        "scale_pos_weight" :3.8,
        "colsample_bytree":0.4, 
        "missing":-1, 
        "eval_metric":'auc',
        "tree_method":'gpu_hist',
        "random_state" : 0}

  xgb_params_2 ={
        "n_estimators":2000,
        "max_depth":12, 
        "learning_rate":0.02, 
        "subsample":0.8,
        "scale_pos_weight" :4,
        "colsample_bytree":0.4, 
        "missing":-1, 
        "eval_metric":'auc',
        "tree_method":'gpu_hist',
        "random_state" : 0}

  CATfeatures =  ['8_slope', 'geology_3', '9_slope', '13_slope', 'aspect_range',
       'slope_max_5_1', 'twi_mean', 'elevation_ratio2', '14_slope',
       '14_lsfactor', 'placurv_min', 'slope_std', 'slope_max', '24_elevation',
       '8_lsfactor', 'slope_mean_5_1', 'elevation_ratio1', 'slope_range',
       'placurv_std', 'elevation_std', 'sdoif_mean', 'twi_max', '17_aspect',
       'twi_median', 'lsfactor_max_5_0', '8_placurv', 'twi_median_5_4',
       'slope_std_5_1', '14_sdoif', 'placurv_min_5_2', '16_elevation',
       '14_placurv', '25_elevation', '10_geology', 'twi_mean_5_0',
       'sdoif_ratio1', 'twi_max_5_1', '15_placurv', '3_geology', '9_lsfactor',
       '3_aspect', 'aspect_std', 'sdoif_std_5_4', 'sdoif_min_5_0',
       '19_geology', 'lsfactor_min_5_0', '13_geology', '9_geology',
       'sdoif_max_5_3', 'lsfactor_max_5_4',
# ------------------------------------------------------------------------------
        '19_placurv', '15_elevation', '13_placurv', 'slope_range_5_1',
       'slope_median_5_1', '7_geology', 'twi_max_5_0', 'slope_mean_5_0',
       '13_lsfactor', '12_geology', '6_aspect', '11_geology',
       'lsfactor_median_5_2', 'elevation_max_5_3', '12_aspect', '4_sdoif',
       'placurv_range', 'twi_median_5_2', 'aspect_ratio1_5_0',
       'lsfactor_range', '6_geology', 'placurv_range_5_2', 'lsfactor_mean_5_4',
       '8_procurv', '11_lsfactor', '21_lsfactor', '5_placurv',
       'sdoif_range_5_1', 'lsfactor_std', 'sdoif_median', 'lsfactor_max',
       'twi_median_5_1', '11_aspect', 'aspect_min_5_0', '5_procurv',
       'elevation_ratio1_5_1', '2_geology', '5_geology', 'aspect_std_5_4',
       'procurv_max', 'elevation_median_5_0', '16_lsfactor', '11_twi',
       'sdoif_median_5_3', 'twi_ratio2', 'twi_ratio2_5_2', 'elevation_max_5_4',
       '15_twi', 'sdoif_min_5_4', 'twi_range',

# ------------------------------------------------------------------------------
        '23_twi', 'slope_mean_5_2', '8_elevation', 'placurv_mean_5_1',
       'lsfactor_min', 'lsfactor_mean', '1_aspect', '25_lsfactor', 'sdoif_max',
       'sdoif_ratio2_5_2', '6_twi', 'sdoif_mean_5_4', 'sdoif_ratio2',
       'elevation_mean', 'sdoif_ratio1_5_2', 'twi_std_5_4', '20_sdoif',
       '9_placurv', 'sdoif_ratio2_5_4', 'sdoif_min_5_3', 'twi_mean_5_4',
       'elevation_mean_5_3', 'sdoif_std_5_0', '22_elevation',
       'lsfactor_min_5_4', '17_elevation', 'elevation_std_5_3',
       'elevation_range', '13_sdoif', '20_geology', 'procurv_ratio2',
       'placurv_median_5_2', '8_sdoif', 'sdoif_mean_5_0', 'twi_max_5_3',
       '1_lsfactor', '20_elevation', 'procurv_mean_5_2',
       'elevation_ratio1_5_4', 'aspect_max_5_4', 'sdoif_range_5_3',
       '10_placurv', '4_procurv', 'aspect_range_5_3', 'twi_ratio1_5_2',
       'placurv_std_5_2', '22_geology', '5_elevation', 'twi_median_5_3',
       'placurv_mean_5_2']

  LGBfeatures = [
        'geology_3', '8_slope', '9_slope', '13_slope', 'sdoif_mean', 'twi_mean',
          'aspect_range', 'placurv_min', 'slope_max_5_1', 'lsfactor_max_5_4',
          '13_lsfactor', 'slope_max_5_2', '8_lsfactor', '1_aspect', 'sdoif_range',
          'elevation_ratio1', 'elevation_std', '14_slope', 'slope_max',
          '20_elevation', 'elevation_ratio2', 'placurv_ratio1', 'placurv_std',
          'twi_mean_5_0', '1_lsfactor', 'placurv_min_5_2', 'lsfactor_min_5_0',
          'sdoif_median', '4_elevation', 'lsfactor_std', 'sdoif_ratio1_5_4',
          '9_placurv', '21_lsfactor', 'aspect_std', 'aspect_ratio1',
          '14_lsfactor', 'lsfactor_range', 'twi_max', 'slope_std', 'twi_std',
          'lsfactor_range_5_1', 'placurv_ratio2_5_0', 'sdoif_ratio2_5_4',
          'placurv_ratio1_5_2', '6_aspect', '8_placurv', '19_placurv',
          '16_aspect', 'sdoif_max_5_0', '5_lsfactor',
    # --------------------------------------------------------------------------------
          '7_aspect', '6_lsfactor', 'lsfactor_mean_5_4', '9_twi', 'slope_std_5_1',
          'lsfactor_max', '14_placurv', '2_aspect', 'sdoif_max', 'lsfactor_min',
          '10_elevation', 'twi_max_5_2', '9_lsfactor', 'placurv_ratio1_5_1',
          'placurv_range', 'sdoif_std', '11_aspect', 'procurv_max_5_2',
          '3_aspect', 'twi_ratio1', 'aspect_min', 'procurv_range', '10_aspect',
          'twi_max_5_0', '4_twi', '25_elevation', 'procurv_std',
          'slope_range_5_1', '15_twi', 'sdoif_ratio2', '16_twi', 'twi_median',
          'slope_range', '12_aspect', 'sdoif_range_5_4', 'sdoif_std_5_4',
          'procurv_mean_5_4', 'aspect_min_5_0', 'aspect_max_5_4',
          'lsfactor_median_5_2', '18_placurv', '15_placurv', 'aspect_ratio1_5_0',
          '25_placurv', 'twi_std_5_2', 'slope_mean_5_2', '11_lsfactor',
          'slope_std_5_2', 'twi_median_5_0', 'procurv_min',
    # --------------------------------------------------------------------------------
        '1_procurv', 'twi_ratio2_5_1', '25_twi', 'twi_ratio1_5_2',
          'twi_range_5_2', '24_lsfactor', 'lsfactor_std_5_1', '10_procurv',
          'elevation_ratio1_5_3', 'twi_range', '12_twi', '9_procurv',
          '16_lsfactor', 'twi_std_5_1', '17_aspect', 'twi_median_5_3',
          'twi_ratio2', '5_elevation', 'procurv_ratio2_5_1', 'procurv_ratio1_5_1',
          'procurv_ratio2', 'lsfactor_mean_5_1', 'placurv_min_5_1',
          'aspect_std_5_3', 'twi_range_5_0', 'procurv_max', 'twi_mean_5_1',
          'procurv_std_5_1', 'placurv_min_5_0', '13_placurv', 'aspect_std_5_4',
          '12_placurv', 'elevation_ratio1_5_1', 'slope_mean_5_0', 'twi_min_5_3',
          'procurv_min_5_1', 'twi_min', '11_twi', 'procurv_range_5_0',
          'procurv_max_5_1', '1_elevation', 'twi_median_5_1',
          'placurv_median_5_1', '23_twi', 'placurv_std_5_2', 'placurv_range_5_2',
          'twi_min_5_2', 'placurv_ratio1_5_4', 'sdoif_ratio1',
          'elevation_std_5_0',

    # --------------------------------------------------------------------------------
          'procurv_ratio2_5_2', '6_placurv', '16_placurv', 'twi_std_5_3',
          'procurv_range_5_2', '22_aspect', 'slope_median_5_2', 'slope_mean_5_1',
          'lsfactor_max_5_3', 'procurv_max_5_4', 'placurv_ratio2',
          'elevation_ratio2_5_3', '19_twi', 'aspect_std_5_2', '20_placurv',
          'aspect_ratio2_5_0', '1_placurv', 'slope_std_5_3', '3_slope',
          'procurv_ratio2_5_4', 'procurv_ratio2_5_0', 'placurv_range_5_3',
          '22_procurv', '5_procurv', 'placurv_median_5_0', 'twi_range_5_3',
          'slope_ratio1', '22_twi', 'aspect_range_5_0', '6_procurv',
          'slope_ratio1_5_1', '15_procurv', 'lsfactor_std_5_4',
          'lsfactor_median_5_1', 'placurv_median_5_2', 'aspect_median_5_1',
          '8_procurv', 'sdoif_min', 'slope_range_5_0', 'placurv_min_5_3',
          'twi_ratio1_5_1', 'procurv_median_5_0', '25_procurv',
          'lsfactor_range_5_0', 'aspect_mean_5_4', '15_slope', 'aspect_ratio2',
          'aspect_ratio1_5_4', 'lsfactor_ratio1', 'aspect_mean']

  XGBfeatures = ['8_slope', 'elevation_std', '10_geology', '5_geology', '19_geology',
       'geology_3', 'elevation_median_5_1', '9_slope', '23_geology',
       '8_elevation', '13_slope', '22_sdoif', '14_geology', '13_geology',
       'elevation_mean_5_1', 'slope_mean_5_1', 'elevation_range', '17_geology',
       '24_sdoif', '15_geology', 'slope_max_5_1', '18_geology', '20_geology',
       '19_sdoif', 'twi_mean', '12_sdoif', 'elevation_mean_5_4', '22_geology',
       '16_sdoif', '14_slope', '7_geology', '21_geology', '17_sdoif',
       '10_elevation', '20_elevation', 'sdoif_mean_5_2', '8_sdoif',
       'sdoif_ratio1', 'sdoif_ratio2_5_4', 'slope_max_5_2', 'sdoif_min_5_3',
       'sdoif_mean_5_4', '20_sdoif', 'geology_5', 'sdoif_ratio1_5_4',
       'slope_median_5_2', '5_elevation', 'elevation_min_5_2', 'sdoif_max_5_4',
       '15_elevation',

      '9_elevation', '11_sdoif', '4_sdoif', '25_sdoif', '18_elevation',
       'sdoif_min_5_1', '14_sdoif', 'sdoif_median_5_4', 'lsfactor_mean_5_4',
       'sdoif_ratio1_5_3', '7_sdoif', 'sdoif_min', '8_geology', '6_elevation',
       '4_elevation', '23_sdoif', '25_elevation', '19_elevation',
       '22_elevation', '1_elevation', 'slope_mean_5_2', '6_sdoif',
       'elevation_ratio2', 'sdoif_max', 'sdoif_median', 'elevation_mean_5_3',
       '21_sdoif', 'aspect_std', 'twi_median', 'sdoif_mean', '16_geology',
       'lsfactor_max_5_4', 'sdoif_std_5_2', '14_elevation', 'slope_max',
       'slope_median_5_1', 'elevation_mean_5_2', 'sdoif_max_5_0',
       'elevation_min_5_4', 'elevation_ratio1', 'elevation_median_5_0',
       '2_sdoif', '2_geology', 'sdoif_ratio2_5_3', '6_aspect', 'placurv_min',
       '24_geology', 'elevation_min_5_0', '9_sdoif', 'sdoif_range',


       '7_elevation', 'sdoif_min_5_4', '6_geology', '1_aspect', '1_lsfactor',
       'sdoif_median_5_1', '18_sdoif', 'sdoif_mean_5_0', 'placurv_std',
       '21_elevation', 'sdoif_range_5_0', 'placurv_min_5_2', 'aspect_min_5_0',
       'aspect_range', 'sdoif_ratio1_5_2', '3_geology', '17_elevation',
       'twi_max', '8_placurv', 'aspect_median_5_3', '4_geology',
       'elevation_median', 'sdoif_ratio2', '5_sdoif', '13_elevation',
       'sdoif_max_5_1', '25_geology', 'lsfactor_median_5_4', 'sdoif_range_5_1',
       'twi_mean_5_2', '7_aspect', '15_sdoif', 'twi_median_5_2',
       'sdoif_std_5_3', 'slope_range', 'sdoif_min_5_0', 'aspect_max_5_1',
       'lsfactor_min_5_0', 'geology_2', 'twi_std', 'geology_nunique',
       'sdoif_median_5_3', '1_sdoif', 'elevation_min_5_3', 'sdoif_range_5_4',
       'elevation_max_5_2', 'aspect_ratio1', '17_aspect', 'sdoif_std_5_4',
       'placurv_mean_5_1',

       'placurv_min_5_1', 'sdoif_range_5_2', 'elevation_mean',
       'slope_mean_5_3', 'sdoif_ratio2_5_0', '9_placurv', 'elevation_max',
       'twi_range', 'sdoif_min_5_2', 'twi_mean_5_0', 'elevation_max_5_4',
       'aspect_ratio2_5_0', '11_aspect', '12_aspect', 'aspect_max_5_2',
       'placurv_ratio1', 'slope_ratio1', 'slope_mean_5_0', 'twi_min_5_0',
       'elevation_min_5_1', 'twi_mean_5_1', '2_aspect', 'aspect_ratio2',
       'twi_max_5_1', 'twi_max_5_2', 'lsfactor_min', '3_aspect',
       'slope_max_5_3', 'elevation_max_5_1', '8_lsfactor', '6_lsfactor',
       'placurv_mean_5_2', 'lsfactor_min_5_4', '21_lsfactor', '1_geology',
       '12_elevation', 'aspect_median_5_1', 'lsfactor_ratio2', '4_twi',
       'placurv_median_5_2', 'aspect_ratio2_5_1', '11_twi', 'procurv_std',
       'lsfactor_ratio2_5_1', '3_elevation', 'aspect_mean_5_1', 'slope_std',
       '24_slope', '19_slope', 'aspect_ratio1_5_0'
      ]

  
